# Generated by Django 3.0.8 on 2021-02-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='contact',
            new_name='content',
        ),
    ]
